In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , classification_report

df = pd.read_csv('https://raw.githubusercontent.com/gabbygab1233/Crop-Recommender/main/Crop_recommendation.csv')
print(df.shape)
df.head

(2200, 8)

<bound method NDFrame.head of         N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]>

In [6]:
print(df['label'].unique())
df.describe()

['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [8]:
# hint: group by label, look at ph column, find the MINIMUM ph per crop
# then sort it so lowest pH appears first!!
df.groupby('label')['ph'].min().sort_values().head(5)

label
mothbeans     3.504752
mango         4.507524
pigeonpeas    4.548202
rice          5.005307
coconut       5.501580
Name: ph, dtype: float64

In [9]:
# let's see the FULL conditions mothbeans needs
df[df['label'] == 'mothbeans'].describe()

,N,P,K,temperature,humidity,ph,rainfall
count,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000
mean,21.440000,48.010000,20.23000,28.194920,53.160418,6.831174,51.198487
std,11.343418,7.547151,3.04795,2.209665,6.994600,1.862163,13.750693
min,0.000000,35.000000,15.00000,24.018254,40.009334,3.504752,30.920140
25%,11.000000,42.750000,18.00000,26.427917,46.726630,5.378557,37.985391
50%,22.000000,48.500000,20.00000,28.370863,53.668190,7.219136,51.182738
75%,30.250000,55.000000,23.00000,30.121721,59.436742,8.366003,64.185059
max,40.000000,60.000000,25.00000,31.999286,64.955854,9.935091,74.443307

In [11]:
X = df.drop('label', axis=1)  # fill in the blank!!
y = df['label']               # fill in the blank!!

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1760
Testing samples: 440

In [17]:
rf_model= RandomForestClassifier(random_state=42)
rf_model.fit (X_train , y_train)
rf_predictions = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test , rf_predictions)
print(f"Random Forest Accuracy: {rf_accuracy*100:.2f}%")

Random Forest Accuracy: 99.32%

In [19]:
print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        23
      banana       1.00      1.00      1.00        21
   blackgram       1.00      1.00      1.00        20
    chickpea       1.00      1.00      1.00        26
     coconut       1.00      1.00      1.00        27
      coffee       1.00      1.00      1.00        17
      cotton       1.00      1.00      1.00        17
      grapes       1.00      1.00      1.00        14
        jute       0.92      1.00      0.96        23
 kidneybeans       1.00      1.00      1.00        20
      lentil       0.92      1.00      0.96        11
       maize       1.00      1.00      1.00        21
       mango       1.00      1.00      1.00        19
   mothbeans       1.00      0.96      0.98        24
    mungbean       1.00      1.00      1.00        19
   muskmelon       1.00      1.00      1.00        17
      orange       1.00      1.00      1.00        14
      papaya       1.00      1.00      1.00        23
  pigeonpeas       1.00      1.00      1.00        23
 pomegranate       1.00      1.00      1.00        23
        rice       1.00      0.89      0.94        19
  watermelon       1.00      1.00      1.00        19

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440